### ISSUE TITLE
Color extractor

### ISSUE THREAD

**Issue by AleksandarStankovski** [MMDevTalks/MovieMate-AleksandarS#1]
Когато отида на преглед на филм, в конзолата ми изписва "node_vibrant_1.default is not a constructor". 
Ако в "tsconfig.json" променя версията от "es5" на по-нова, тогава всичко е наред.

**Comment by angelnikolov** [comment]
Хмм, а как импортваш Vibrant?

**Comment by AleksandarStankovski** [comment]
В tsconfig.json добавих "allowSyntheticDefaultImports": true. След това в директивата написах import Vibrant from 'node-vibrant';

**Comment by angelnikolov** [comment]
Хмм, интересно, а версията на `node-vibrant`? Би трябвало да се билдва в es5

**Comment by AleksandarStankovski** [comment]
Версията е 3.0.0. 
Може и да изпускам нещо, но в момента не се сещам. Ще прегледам отново качения проект и ще проверя дали всичко е еднакво.
